/**
 * Browser entry point for the manim-nano demo.
 *
 * Wires the textarea + "Render" button to the WebAssembly export `render_gif`,
 * turns the returned bytes into an object URL, and shows the resulting GIF.
 *
 * The wasm glue (`../pkg/manim_nano.js` + `manim_nano_bg.wasm`) is produced by:
 *
 *     wasm-pack build --target web --features wasm --out-dir web/pkg
 *
 * See web/README.md for the full build + serve steps.
 */

// The generated glue module: a default `init` plus the named exports we marked
// with `#[wasm_bindgen]`. The `?` keeps the type checker happy before the glue
// has been generated; at runtime the file is always present when served.
// @ts-expect-error — generated by wasm-pack; not present until you build.
import init, { render_gif, version } from "../pkg/manim_nano.js";

/** Strongly-typed signatures for the wasm exports we consume. */
type RenderGif = (
  text: string,
  width: number,
  height: number,
  fps: number,
) => Uint8Array;
type Version = () => string;

const renderGif = render_gif as RenderGif;
const wasmVersion = version as Version;

/** Fixed render settings for the demo. */
const RENDER_CONFIG = {
  width: 640,
  height: 360,
  fps: 30,
} as const satisfies Readonly<{
  width: number;
  height: number;
  fps: number;
}>;

/** UI state modelled as a discriminated union. */
type AppState =
  | { readonly status: "idle" }
  | { readonly status: "rendering" }
  | { readonly status: "done"; readonly url: string }
  | { readonly status: "error"; readonly message: string };

/** Looks up a required element by id, narrowing to the expected element type. */
function requireElement<T extends Element>(
  id: string,
  ctor: new () => T,
): T {
  const el = document.getElementById(id);
  if (el === null) {
    throw new Error(`missing #${id} in the page`);
  }
  if (!(el instanceof ctor)) {
    throw new Error(`#${id} is not a ${ctor.name}`);
  }
  return el;
}

interface Ui {
  readonly prompt: HTMLTextAreaElement;
  readonly button: HTMLButtonElement;
  readonly status: HTMLElement;
  readonly output: HTMLImageElement;
  readonly about: HTMLElement;
}

/** The currently displayed object URL, so we can revoke it before replacing. */
let activeUrl: string | null = null;

/** Applies a state transition to the DOM. Pure side effects, no return value. */
function applyState(ui: Ui, state: AppState): void {
  // Always revoke the previous URL unless we are keeping this exact one.
  if (activeUrl !== null && !(state.status === "done" && state.url === activeUrl)) {
    URL.revokeObjectURL(activeUrl);
    activeUrl = null;
  }

  switch (state.status) {
    case "idle": {
      ui.button.disabled = false;
      ui.status.textContent = "";
      ui.status.classList.remove("error");
      return;
    }
    case "rendering": {
      ui.button.disabled = true;
      ui.status.textContent = "Rendering…";
      ui.status.classList.remove("error");
      return;
    }
    case "done": {
      ui.button.disabled = false;
      ui.status.textContent = "Done.";
      ui.status.classList.remove("error");
      ui.output.src = state.url;
      ui.output.hidden = false;
      activeUrl = state.url;
      return;
    }
    case "error": {
      ui.button.disabled = false;
      ui.status.textContent = state.message;
      ui.status.classList.add("error");
      return;
    }
  }
}

/** Renders the current prompt to a GIF object URL, returning the next state. */
function renderToState(prompt: string): AppState {
  const text = prompt.trim();
  const description =
    text.length > 0
      ? text
      : "Draw a red circle, then move it right while a blue square fades in";

  try {
    const bytes = renderGif(
      description,
      RENDER_CONFIG.width,
      RENDER_CONFIG.height,
      RENDER_CONFIG.fps,
    );
    if (bytes.length === 0) {
      return {
        status: "error",
        message: "The engine produced no output for that description.",
      };
    }
    // Copy into a fresh ArrayBuffer-backed view so the Blob owns its bytes.
    const blob = new Blob([new Uint8Array(bytes)], { type: "image/gif" });
    const url = URL.createObjectURL(blob);
    return { status: "done", url };
  } catch (cause) {
    const message = cause instanceof Error ? cause.message : String(cause);
    return { status: "error", message: `Render failed: ${message}` };
  }
}

/** Boots the wasm module and wires up the UI. */
async function main(): Promise<void> {
  const ui: Ui = {
    prompt: requireElement("prompt", HTMLTextAreaElement),
    button: requireElement("render", HTMLButtonElement),
    status: requireElement("status", HTMLElement),
    output: requireElement("output", HTMLImageElement),
    about: requireElement("about", HTMLElement),
  };

  await init();
  ui.about.textContent = `manim-nano v${wasmVersion()} · runs offline · free forever`;

  applyState(ui, { status: "idle" });

  ui.button.addEventListener("click", () => {
    applyState(ui, { status: "rendering" });
    // Defer the (synchronous) wasm call one frame so the "Rendering…" label
    // actually paints before the main thread blocks.
    requestAnimationFrame(() => {
      applyState(ui, renderToState(ui.prompt.value));
    });
  });
}

void main();
